name: Azure Pipelines

trigger:
- main

pool: TrungNQ72-Udacity-Project3-SelfHost

variables:
  - group: MyTerraformVars  # Reference your variable group here

stages:
  - stage: Build
    jobs:
      - job: BuildInfrastructure
        steps:
          # Install Terraform on the pipeline agent 
          - task: TerraformInstaller@0
            displayName: 'Terraform installation'
            inputs:
              terraformVersion: '1.2.9'
          
          # Explicit Azure login using service principal
          - task: AzureCLI@2
            inputs:
              azureSubscription: '$(azureServiceConnectionId)'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az login --service-principal -u $(client_id) -p $(client_secret) --tenant $(tenant_id)

          # Run Terraform Init
          - task: TerraformTaskV4@4
            displayName: 'Terraform init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
              backendServiceArm: '$(azureServiceConnectionId)'
              backendAzureRmResourceGroupName: 'trungnq72-resource_group_project_3'
              backendAzureRmStorageAccountName: 'tfstate39711214'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'test.terraform.tfstate'
              commandOptions: '-input=false -backend-config="client_id=$(client_id)" -backend-config="client_secret=$(client_secret)" -backend-config="tenant_id=$(tenant_id)"'

          # Run Terraform Apply
          - task: TerraformTaskV4@4
            displayName: 'Terraform apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
              environmentServiceNameAzureRM: '$(azureServiceConnectionId)'
              commandOptions: '-input=false -var-file=$(tfvars.secureFilePath) -auto-approve'
